# udagram-api-feed
# Build
- docker build -t udagram-api-feed ./udagram-api-feed
# Tagging
- docker tag udagram-api-feed sudkul/udagram-api-feed:v1
# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push sudkul/udagram-api-feed:v1
# udagram-api-user
# Build
- docker build -t udagram-api-user ./udagram-api-user
# Tagging
- docker tag udagram-api-user sudkul/udagram-api-user:v1
# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push sudkul/udagram-api-user:v1
# udagram-frontend
# Build
- docker build -t udagram-frontend ./udagram-frontend
# Tagging
- docker tag udagram-frontend sudkul/udagram-frontend:v1
# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push sudkul/udagram-frontend:v1
# udagram-reverseproxy
# Build
- docker build -t udagram-reverseproxy ./udagram-reverseproxy
# Tagging
- docker tag udagram-reverseproxy sudkul/udagram-reverseproxy:v1
# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push sudkul/udagram-reverseproxy:v1